export const RSS_SOURCES = [
  // 顶级AI科技媒体
  { url: 'https://techcrunch.com/category/artificial-intelligence/feed/', source: 'TechCrunch AI', category: 'news' },
  { url: 'https://venturebeat.com/ai/feed/', source: 'VentureBeat AI', category: 'news' },
  { url: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml', source: 'The Verge AI', category: 'news' },
  { url: 'https://feeds.feedburner.com/oreilly/radar', source: "O'Reilly Radar", category: 'tech' },
  { url: 'https://machinelearningmastery.com/feed/', source: 'ML Mastery', category: 'tutorial' },
  
  // AI研究与工具
  { url: 'https://huggingface.co/blog/feed.xml', source: 'HuggingFace Blog', category: 'research' },
  { url: 'https://openai.com/blog/rss.xml', source: 'OpenAI Blog', category: 'research' },
  { url: 'https://blog.google/technology/ai/rss/', source: 'Google AI Blog', category: 'research' },
  { url: 'https://www.anthropic.com/rss.xml', source: 'Anthropic', category: 'research' },
  { url: 'https://stability.ai/blog/rss', source: 'Stability AI', category: 'tools' },
  
  // AI新闻聚合
  { url: 'https://aiweekly.co/issues.rss', source: 'AI Weekly', category: 'news' },
  { url: 'https://jack-clark.net/feed/', source: 'Import AI', category: 'newsletter' },
  { url: 'https://buttondown.email/ainews/rss', source: 'AI News', category: 'news' },
  
  // 开发者社区
  { url: 'https://github.blog/feed/', source: 'GitHub Blog', category: 'dev' },
  { url: 'https://www.wired.com/feed/tag/ai/rss', source: 'Wired AI', category: 'news' },
  { url: 'https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss', source: 'IEEE AI', category: 'research' },
]

export const AI_TOOLS = [
  {
    name: 'ChatGPT',
    description: 'OpenAI\'s powerful conversational AI for writing, coding, and analysis',
    url: 'https://chat.openai.com',
    affiliate_url: null,
    category: 'Chat AI',
    tags: ['chat', 'writing', 'coding'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'Claude',
    description: 'Anthropic\'s AI assistant with long context and nuanced reasoning',
    url: 'https://claude.ai',
    affiliate_url: null,
    category: 'Chat AI',
    tags: ['chat', 'writing', 'analysis'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'Midjourney',
    description: 'State-of-the-art AI image generation with stunning artistic quality',
    url: 'https://midjourney.com',
    affiliate_url: null,
    category: 'Image AI',
    tags: ['image', 'art', 'design'],
    pricing: 'Paid',
    featured: true,
  },
  {
    name: 'Cursor',
    description: 'AI-first code editor built for pair programming with AI',
    url: 'https://cursor.sh',
    affiliate_url: 'https://cursor.sh/?ref=ainewshub',
    category: 'Coding AI',
    tags: ['coding', 'productivity', 'IDE'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'Perplexity AI',
    description: 'AI-powered search engine with real-time web access',
    url: 'https://perplexity.ai',
    affiliate_url: null,
    category: 'Search AI',
    tags: ['search', 'research'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'Jasper AI',
    description: 'AI writing assistant for marketing teams and content creators',
    url: 'https://www.jasper.ai',
    affiliate_url: 'https://www.jasper.ai/?fpr=ainewshub',
    category: 'Writing AI',
    tags: ['writing', 'marketing', 'content'],
    pricing: 'Paid',
    featured: false,
  },
  {
    name: 'ElevenLabs',
    description: 'AI voice cloning and text-to-speech with human-like quality',
    url: 'https://elevenlabs.io',
    affiliate_url: null,
    category: 'Voice AI',
    tags: ['voice', 'audio', 'tts'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'Runway ML',
    description: 'AI video generation and creative tools for filmmakers',
    url: 'https://runwayml.com',
    affiliate_url: null,
    category: 'Video AI',
    tags: ['video', 'creative', 'film'],
    pricing: 'Freemium',
    featured: true,
  },
  {
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code in real-time in your editor',
    url: 'https://github.com/features/copilot',
    affiliate_url: null,
    category: 'Coding AI',
    tags: ['coding', 'productivity'],
    pricing: 'Paid',
    featured: false,
  },
  {
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation you can run locally or in cloud',
    url: 'https://stability.ai',
    affiliate_url: null,
    category: 'Image AI',
    tags: ['image', 'open-source'],
    pricing: 'Free',
    featured: false,
  },
]
